BUTTON_BOLD_FONT = 'Helvetica 14 bold'
BUTTON_FONT = 'Helvetica 14'
LARGE_BOLD_FONT = 'Helvetica 16 bold'
LARGE_FONT = 'Helvetica 18'
NORM_BOLD_FONT = 'Helvetica 14 bold'
NORM_FONT = 'Helvetica 16'
SMALL_BOLD_FONT = 'Helvetica 10 bold'
SMALL_FONT = 'Helvetica 10'